# Extra utilities configuration

# set to True to print config tree with Rich library
print_config: True

# set to True to ignore warnings
ignore_warnings: False

# set to True to enforce tags from command line
enforce_tags: False

# pretty print config at the top of the run
# uses Rich library under the hood
print_config_tree: True
