# @package _global_

# Main configuration file for evaluation
# This determines how config is composed when running: python src/eval.py

defaults:
  - _self_
  - data: mnist.yaml
  - model: mnist.yaml
  - logger: null  # set logger here or use command line
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml

  # optional local config for machine/user specific settings
  - optional local: default.yaml

# task name, determines output directory path
task_name: "eval"

# tags to help you identify your experiments
tags: ["dev"]

# checkpoint path for evaluation (required for eval)
ckpt_path: ???

# seed for random number generators
seed: null
